<?php 
//pocetna stranica
$model["cntr"]["pocetnaID"] = 1;
 
//imaginarna 404 stranica
$model["cntr"]["nemaID"] = 6;

//folder za kontroler
$model["cntr"]["kontroler"] = "kontr/";

//folder za view
$model["cntr"]["prikaz"] = "prikaz/";

//folder za model stranica
$model["cntr"]["model"] = "model/";

//folder za template
$model["cntr"]["template"] = "template/";

//broj proizvoda na stranici
$model["cntr"]["brP"] = 9;

?>